[package]
name = "scop"
version = "0.1.0"
edition = "2024"

[dependencies]
# Vulkan
ash = "0.38"
ash-window = "0.13.0"

# Windowing
winit = "0.30.12"

# Utils
raw-window-handle = "0.6.2"

[dev-dependencies]
